In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'], 'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [3]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [4]:
dummies = pd.get_dummies(df['key'],prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [5]:
df_with_dummies = df[['data1']].join(dummies)
df_with_dummies

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

# When a row belongs to multiple calsses i.e., multilabel varible

In [8]:
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None,names=['movie_id','title','genres'])
movies[:10]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [13]:
all_genres=[]
for x in movies['genres']:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [15]:
zero_matrix = np.zeros((len(movies),len(genres)))
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
dummies = pd.DataFrame(zero_matrix,columns=genres)
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
5           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
6           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
7           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
8           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
9           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
10          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
11          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
12          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
13          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
14          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
15          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
16          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
17          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
18          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
19          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
20          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
21          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
22          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
23          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
24          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
25          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
26          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
27          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
28          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
29          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3853        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3854        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3855        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3856        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3857        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3858        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3859        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3860        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3861        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3862        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3863        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3864        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3865        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3866        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3867        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3868        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3869        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3870        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3871        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3872        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3873        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3874        0.0         0.0    

In [17]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [18]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [19]:
enumerate(movies.genres)

In [20]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           1.0         1.0     1.0        0.0      0.0      0.0    0.0   
1           0.0         1.0     0.0        1.0      1.0      0.0    0.0   
2           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
3           0.0         0.0     1.0        0.0      0.0      0.0    1.0   
4           0.0         0.0     1.0        0.0      0.0      0.0    0.0   
5           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
6           0.0         0.0     1.0        0.0      0.0      1.0    0.0   
7           0.0         1.0     0.0        1.0      0.0      0.0    0.0   
8           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
9           0.0         0.0     0.0        1.0      0.0      0.0    0.0   
10          0.0         0.0     1.0        0.0      0.0      1.0    1.0   
11          0.0         0.0     1.0        0.0      0.0      0.0    0.0   
12          1.0         1.0     0.0        0.0      0.0      0.0    0.0   
13          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
14          0.0         0.0     0.0        1.0      0.0      1.0    0.0   
15          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
16          0.0         0.0     0.0        0.0      0.0      1.0    1.0   
17          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
18          0.0         0.0     1.0        0.0      0.0      0.0    0.0   
19          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
20          0.0         0.0     1.0        0.0      0.0      0.0    1.0   
21          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
22          0.0         0.0     0.0        0.0      0.0      0.0    0.0   
23          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
24          0.0         0.0     0.0        0.0      0.0      1.0    1.0   
25          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
26          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
27          0.0         0.0     0.0        0.0      0.0      1.0    0.0   
28          0.0         0.0     0.0        1.0      0.0      0.0    0.0   
29          0.0         0.0     0.0        0.0      0.0      0.0    1.0   
...         ...         ...     ...        ...      ...      ...    ...   
3853        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3854        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3855        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3856        0.0         0.0     0.0        1.0      0.0      0.0    0.0   
3857        0.0         0.0     0.0        1.0      0.0      0.0    0.0   
3858        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3859        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3860        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3861        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3862        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3863        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3864        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3865        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3866        0.0         0.0     0.0        0.0      0.0      0.0    1.0   
3867        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3868        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3869        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3870        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3871        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3872        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3873        0.0         0.0     1.0        0.0      0.0      0.0    0.0   
3874        0.0         0.0    

In [23]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

# Combining Get Dummies with discretization

In [24]:
np.random.seed(12345)
values = np.random.randn(10)
values

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [25]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           0
1           0           0           1           0           0
2           0           0           0           0           0
3           0           0           0           0           0
4           0           0           0           0           0
5           0           0           0           0           0
6           1           0           0           0           0
7           0           1           0           0           0
8           0           0           0           1           0
9           0           0           0           0           0