In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list =  list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 215 ms


In [3]:
%time for _ in range(10): my_list2 = [i*2 for i in my_list]

Wall time: 2.23 s


In [4]:
arr1 = np.random.randn(2,5)
arr1

array([[-1.54886329, -0.25517222, -1.032759  ,  0.05570272,  0.9742597 ],
       [ 0.20706271,  1.67503746,  0.63680304, -0.48229009, -1.65214922]])

In [5]:
arr1*10

array([[-15.48863288,  -2.55172217, -10.32759002,   0.55702717,
          9.74259696],
       [  2.07062706,  16.75037462,   6.36803036,  -4.82290087,
        -16.52149219]])

In [6]:
arr1+arr1

array([[-3.09772658, -0.51034443, -2.065518  ,  0.11140543,  1.94851939],
       [ 0.41412541,  3.35007492,  1.27360607, -0.96458017, -3.30429844]])

In [7]:
arr1.shape

(2, 5)

In [9]:
arr1.dtype

dtype('float64')

In [11]:
arr1 = np.array([1,1,2.3,4.4,5,6,7.5,9.9])
arr1

array([1. , 1. , 2.3, 4.4, 5. , 6. , 7.5, 9.9])

In [12]:
arr2 = np.array([2,4,5,6,7,1,6],dtype=np.float64)
arr2

array([2., 4., 5., 6., 7., 1., 6.])

In [16]:
arr1 = arr1.astype(np.int64)

In [17]:
arr1.dtype

dtype('int64')

In [18]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.63234836e-321],
       [1.13526775e-311, 7.55243368e+024, 1.13647398e-311]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((1,3))

array([[1., 1., 1.]])

In [22]:
arr2.ndim

1

In [24]:
stringarray = np.array(['I am legend','THis is batman'], dtype=np.string_)
stringarray

array([b'I am legend', b'THis is batman'], dtype='|S14')

In [27]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
arr2 = np.array([[1,3,4],[4,5,7]])

In [34]:
arr2>arr

array([[False,  True,  True],
       [False, False,  True]])

In [4]:
arr3d = np.arange(0,9).reshape((3,3))
arr3d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr3d[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
arr3d[:2,:1]

array([[0],
       [3]])

In [8]:
arr3d[1,:2]

array([3, 4])

In [9]:
arr3d[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [47]:
names =  np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)

In [11]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [12]:
data

array([[ 0.63213713,  0.66048865,  1.19117335,  1.23456274],
       [ 0.1397168 ,  0.90209184,  1.93399962,  0.14460979],
       [-1.5328744 ,  0.61984106,  0.08681488,  1.32333097],
       [-1.74343566, -0.25574346, -0.06037638,  0.5831549 ],
       [ 0.59506   , -0.87794422, -1.32882261,  0.17192322],
       [-0.96832247,  0.04007444,  1.03249818, -1.05554666],
       [ 0.71221706,  0.75018634,  1.24243777, -1.9289293 ]])

In [13]:
data[names == 'Joe']

array([[ 0.1397168 ,  0.90209184,  1.93399962,  0.14460979],
       [-0.96832247,  0.04007444,  1.03249818, -1.05554666],
       [ 0.71221706,  0.75018634,  1.24243777, -1.9289293 ]])

In [14]:
data[names ==  'Joe', 2:]

array([[ 1.93399962,  0.14460979],
       [ 1.03249818, -1.05554666],
       [ 1.24243777, -1.9289293 ]])

In [15]:
data[names != 'Joe']

array([[ 0.63213713,  0.66048865,  1.19117335,  1.23456274],
       [-1.5328744 ,  0.61984106,  0.08681488,  1.32333097],
       [-1.74343566, -0.25574346, -0.06037638,  0.5831549 ],
       [ 0.59506   , -0.87794422, -1.32882261,  0.17192322]])

In [17]:
data[~(names == 'Joe')]

array([[ 0.63213713,  0.66048865,  1.19117335,  1.23456274],
       [-1.5328744 ,  0.61984106,  0.08681488,  1.32333097],
       [-1.74343566, -0.25574346, -0.06037638,  0.5831549 ],
       [ 0.59506   , -0.87794422, -1.32882261,  0.17192322]])

In [19]:
data[(names == 'Joe') | (names == 'Will')]

array([[ 0.1397168 ,  0.90209184,  1.93399962,  0.14460979],
       [-1.5328744 ,  0.61984106,  0.08681488,  1.32333097],
       [ 0.59506   , -0.87794422, -1.32882261,  0.17192322],
       [-0.96832247,  0.04007444,  1.03249818, -1.05554666],
       [ 0.71221706,  0.75018634,  1.24243777, -1.9289293 ]])

In [20]:
data[data<0]

array([-1.5328744 , -1.74343566, -0.25574346, -0.06037638, -0.87794422,
       -1.32882261, -0.96832247, -1.05554666, -1.9289293 ])

In [21]:
data[data<0]=0

In [22]:
data

array([[0.63213713, 0.66048865, 1.19117335, 1.23456274],
       [0.1397168 , 0.90209184, 1.93399962, 0.14460979],
       [0.        , 0.61984106, 0.08681488, 1.32333097],
       [0.        , 0.        , 0.        , 0.5831549 ],
       [0.59506   , 0.        , 0.        , 0.17192322],
       [0.        , 0.04007444, 1.03249818, 0.        ],
       [0.71221706, 0.75018634, 1.24243777, 0.        ]])

In [23]:
data[[1,3,2,5]]

array([[0.1397168 , 0.90209184, 1.93399962, 0.14460979],
       [0.        , 0.        , 0.        , 0.5831549 ],
       [0.        , 0.61984106, 0.08681488, 1.32333097],
       [0.        , 0.04007444, 1.03249818, 0.        ]])

In [24]:
data

array([[0.63213713, 0.66048865, 1.19117335, 1.23456274],
       [0.1397168 , 0.90209184, 1.93399962, 0.14460979],
       [0.        , 0.61984106, 0.08681488, 1.32333097],
       [0.        , 0.        , 0.        , 0.5831549 ],
       [0.59506   , 0.        , 0.        , 0.17192322],
       [0.        , 0.04007444, 1.03249818, 0.        ],
       [0.71221706, 0.75018634, 1.24243777, 0.        ]])

In [25]:
data.T

array([[0.63213713, 0.1397168 , 0.        , 0.        , 0.59506   ,
        0.        , 0.71221706],
       [0.66048865, 0.90209184, 0.61984106, 0.        , 0.        ,
        0.04007444, 0.75018634],
       [1.19117335, 1.93399962, 0.08681488, 0.        , 0.        ,
        1.03249818, 1.24243777],
       [1.23456274, 0.14460979, 1.32333097, 0.5831549 , 0.17192322,
        0.        , 0.        ]])

In [26]:
arr = np.random.randn(4,4)
arr

array([[-0.28197314, -0.52927244,  0.93499515,  0.00778545],
       [-0.83965447, -0.64421548, -1.16731922, -0.90434918],
       [ 0.66666597,  2.01957863, -1.74613592, -1.80109636],
       [-2.06889303, -0.63186126, -0.88649867,  0.41620445]])

In [27]:
arr > 0

array([[False, False,  True,  True],
       [False, False, False, False],
       [ True,  True, False, False],
       [False, False, False,  True]])

In [28]:
np.where(arr>0,2,-2)

array([[-2, -2,  2,  2],
       [-2, -2, -2, -2],
       [ 2,  2, -2, -2],
       [-2, -2, -2,  2]])

In [29]:
np.where(arr>0,2,arr)

array([[-0.28197314, -0.52927244,  2.        ,  2.        ],
       [-0.83965447, -0.64421548, -1.16731922, -0.90434918],
       [ 2.        ,  2.        , -1.74613592, -1.80109636],
       [-2.06889303, -0.63186126, -0.88649867,  2.        ]])

In [30]:
arr.mean()

-0.4660024701214561

In [31]:
np.mean(arr)

-0.4660024701214561

In [32]:
arr.mean(0)

array([-0.63096367,  0.05355736, -0.71623966, -0.57036391])

In [33]:
arr.mean(1)

array([ 0.03288376, -0.88888459, -0.21524692, -0.79276213])

In [34]:
arr.std()

1.046262689758972

In [35]:
arr.var()

1.094665615981679

In [36]:
arr.cumsum()

array([-0.28197314, -0.81124557,  0.12374958,  0.13153503, -0.70811945,
       -1.35233493, -2.51965415, -3.42400333, -2.75733736, -0.73775873,
       -2.48389465, -4.28499101, -6.35388404, -6.9857453 , -7.87224397,
       -7.45603952])

In [37]:
arr.cumsum(0)

array([[-0.28197314, -0.52927244,  0.93499515,  0.00778545],
       [-1.12162761, -1.17348792, -0.23232407, -0.89656373],
       [-0.45496165,  0.84609072, -1.97845999, -2.69766009],
       [-2.52385468,  0.21422946, -2.86495866, -2.28145564]])

In [38]:
arr.cumprod(1)

array([[-2.81973138e-01,  1.49240609e-01,  1.39539246e-01,
         1.08637579e-03],
       [-8.39654475e-01,  5.40918410e-01, -6.31424457e-01,
         5.71028190e-01],
       [ 6.66665966e-01,  1.34638434e+00, -2.35097005e+00,
         4.23432359e+00],
       [-2.06889303e+00,  1.30725336e+00, -1.15887837e+00,
        -4.82330333e-01]])

In [39]:
arr = np.random.randn(100)

In [40]:
(arr>0).sum()

47

In [41]:
(arr>0).any()

True

In [42]:
(arr>0).all()

False

In [43]:
arr

array([-1.51939283, -0.53396291, -0.51268209, -0.0939664 , -0.51693149,
       -1.82992739, -0.89886817,  0.59854003,  0.72612142, -0.36236423,
       -0.81952569, -0.28645923,  0.29142349, -0.5660996 ,  0.456148  ,
       -0.07748426, -0.24895481,  0.22727809,  0.94724866, -1.19841813,
        1.2103845 ,  0.13476245,  1.17008358,  0.8199372 ,  0.38148103,
        0.0377067 ,  0.32283246,  2.29249031,  0.48678218,  0.87946236,
        0.95148916, -1.83194847, -0.48961743, -0.1980595 ,  0.48871787,
        2.00717815,  0.26871995, -1.731255  ,  0.47120919, -1.04949934,
       -0.65145489,  1.98126315,  0.38607299,  1.00212347,  0.54059   ,
       -0.84714266,  1.14327675, -1.05478962, -1.47829535, -1.55405078,
       -1.48582135,  0.80556073,  0.32767329, -0.3168562 , -1.07933224,
        0.25374671, -0.88578455, -0.67531966, -0.11642156, -0.95608299,
       -0.02677521,  0.49382639, -0.17695448, -1.18602185,  0.14445703,
       -0.83732912,  0.0530451 , -0.22231744, -0.997296  , -0.61

In [45]:
arr.sort()
arr

array([-2.65768465, -1.83194847, -1.82992739, -1.79637523, -1.731255  ,
       -1.63348333, -1.55405078, -1.54656638, -1.51939283, -1.48582135,
       -1.47829535, -1.19841813, -1.18602185, -1.14806144, -1.13864109,
       -1.07933224, -1.05478962, -1.04949934, -1.03977803, -1.01307112,
       -0.997296  , -0.95608299, -0.93521699, -0.89886817, -0.88578455,
       -0.84714266, -0.83732912, -0.81952569, -0.67845711, -0.67531966,
       -0.65145489, -0.6112915 , -0.5660996 , -0.53763649, -0.53396291,
       -0.51693149, -0.51268209, -0.48961743, -0.43474911, -0.36236423,
       -0.3168562 , -0.28645923, -0.28604931, -0.24895481, -0.22231744,
       -0.19880291, -0.1980595 , -0.17695448, -0.11642156, -0.0939664 ,
       -0.07748426, -0.04167644, -0.02677521,  0.0377067 ,  0.04745756,
        0.0530451 ,  0.13476245,  0.14445703,  0.19221556,  0.22727809,
        0.25374671,  0.255645  ,  0.26871995,  0.29142349,  0.32283246,
        0.32767329,  0.38148103,  0.38607299,  0.38750226,  0.45

In [46]:
np.sort(arr2d)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [49]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [50]:
arr2.dot(arr)

101.88889041267348

In [51]:
np.random.seed(100)

In [52]:
state1 = np.random.RandomState(1234)

In [61]:
state1.randn(9).reshape((3,3))

array([[-0.20849876,  1.03380073, -2.40045363],
       [ 2.03060362, -1.14263129,  0.21188339],
       [ 0.70472062, -0.78543521,  0.46205974]])

In [63]:
import random
position = 0
walk=[position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
walk

[0,
 1,
 0,
 -1,
 0,
 1,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 5,
 6,
 5,
 4,
 3,
 4,
 3,
 2,
 1,
 2,
 3,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -6,
 -7,
 -8,
 -9,
 -8,
 -7,
 -8,
 -7,
 -8,
 -7,
 -6,
 -7,
 -8,
 -9,
 -8,
 -9,
 -10,
 -9,
 -8,
 -7,
 -6,
 -5,
 -6,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -5,
 -6,
 -7,
 -8,
 -9,
 -10,
 -11,
 -10,
 -11,
 -12,
 -11,
 -12,
 -13,
 -12,
 -11,
 -12,
 -13,
 -12,
 -13,
 -12,
 -13,
 -14,
 -15,
 -16,
 -17,
 -16,
 -17,
 -16,
 -15,
 -14,
 -15,
 -16,
 -15,
 -14,
 -15,
 -16,
 -15,
 -14,
 -13,
 -14,
 -15,
 -14,
 -13,
 -12,
 -11,
 -12,
 -13,
 -14,
 -13,
 -12,
 -11,
 -12,
 -13,
 -14,
 -15,
 -14,
 -15,
 -14,
 -13,
 -12,
 -11,
 -10,
 -11,
 -10,
 -11,
 -12,
 -13,
 -12,
 -11,
 -12,
 -13,
 -14,
 -15,
 -16,
 -15,
 -16,
 -15,
 -16,
 -15,
 -16,
 -17,
 -18,
 -19,
 -20,
 -21,
 -20,
 -21,
 -20,
 -21,
 -22,
 -23,
 -22,
 -21,
 -22,
 -21,
 -20,
 -19,
 -18,
 -17,
 -16,
 -17,
 -18,
 -19,
 -20,
 -21,
 -22,
 -23,
 -22,
 -23,
 -24,
 -25,
 -26,
 

In [66]:
nsteps = 100
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()
walk

array([  1,   0,  -1,  -2,  -3,  -4,  -3,  -2,  -3,  -4,  -3,  -4,  -5,
        -6,  -5,  -6,  -5,  -6,  -5,  -4,  -5,  -6,  -7,  -6,  -7,  -8,
        -9, -10,  -9, -10, -11, -10,  -9, -10,  -9,  -8,  -7,  -8,  -9,
        -8,  -9, -10,  -9, -10,  -9, -10,  -9, -10, -11, -10, -11, -10,
        -9,  -8,  -7,  -8,  -7,  -8,  -9,  -8,  -7,  -8,  -9, -10, -11,
       -10,  -9,  -8,  -7,  -8,  -9,  -8,  -9,  -8,  -7,  -6,  -7,  -6,
        -7,  -6,  -7,  -6,  -7,  -6,  -5,  -6,  -7,  -8,  -7,  -8,  -9,
        -8,  -9, -10,  -9,  -8,  -7,  -8,  -9,  -8], dtype=int32)

In [67]:
walk.min()

-11

In [68]:
walk.max()

1

In [69]:
(np.abs(walk)>= 10).argmax()

27

In [72]:
nwalks = 100
nsteps =100
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)
walks

array([[  1,   0,   1, ...,  10,   9,   8],
       [ -1,   0,  -1, ..., -12, -13, -14],
       [  1,   2,   1, ...,  -8,  -7,  -8],
       ...,
       [ -1,   0,   1, ...,  14,  13,  14],
       [  1,   2,   3, ..., -10, -11, -12],
       [ -1,   0,  -1, ..., -16, -17, -18]], dtype=int32)

In [73]:
walks.max()

29

In [74]:
walks.min()

-21